Abraxas-365/langchain-rust

src/agent/chat/chat_agent.rs, src/chain/conversational/mod.rs, src/chain/llm_chain.rs, src/llm/openai/mod.rs
Run ollama server and run the following command. This should allow chat completion api to use ollama.
```rust
use anyhow::Result;
use langchain_rust::{language_models::llm::LLM, llm::openai::OpenAI};
#[tokio::main]
async fn main() -> Result<()> {
let open_ai = OpenAI::default()
.with_api_base("http://localhost:11434/v1")
.with_api_key("ollama")
.with_model("llama2");
let resp = open_ai
.invoke("What is the captial of France?")
.await
.unwrap();
println!("{resp}");
Ok(())
}
```
Note: ollama doesn't support all features:
* https://github.com/ollama/ollama/issues/1729
* https://github.com/ollama/ollama/issues/2416
=> add with_api_base and with_org_id and pass model as string for llm::openai to support ollama and other open ai compatible api

.github/workflows/ci.yml
For example: to publish a new version `2.2.5`:
* Update Cargo.toml version to `2.2.5`.
* Commit
* Create a tag called `v2.2.5`.
* Push commits
* Push tags
I can't access settings so feel free to set `CRATES_TOKEN` secret in the GitHub settings. If you don't want publish_create let me know and I'm more than happy to remove it.
=> add GitHub workflows CI support

src/embedding/mod.rs, src/embedding/ollama/mod.rs, src/embedding/ollama/ollama_embedder.rs
This add support for ollama embedding based of https://js.langchain.com/docs/integrations/text_embedding/ollama.
Ollama doesn't yet support OpenAI compatibility for embeddings api so adding one that directly calls ollama apis. When the compatibility is supported we can think of removing this if we want.
Ref:
- https://github.com/ollama/ollama/issues/2416
- https://github.com/ollama/ollama/pull/2925
Since the ollama api doesn't support batch embedding apis, we manually loop and make a request in serial order and send it.
Ref:
- https://github.com/ollama/ollama/pull/2924
Usage:
```rust
let embedding = OllamaEmbedder::default();
let result = embedding
.embed_documents(&vec!["hello".into(), "world".into()])
.await
.unwrap();
println!("{:?}", result);
let result = embedding
.embed_query("What …
```
=> add support for ollama embeddings

src/document_loaders/document_loader.rs, src/document_loaders/mod.rs, src/document_loaders/text_loader/mod.rs, src/document_loaders/text_loader/text_loader.rs, src/lib.rs, src/text_splitter/text_splitter.rs
This commit introduces the document loaders module that includes two core components:
- The document_loader that provides the load and load_and_split functions with an asynchronous trait implementation.
- The text_loader that reads an AsyncRead resource and interfaces with the document_loader to load the documents.
The text_splitter trait has been adjusted to include sending and synchronization.
Refer to the individual files for a detailed implementation.
This update does not affect other parts of the system.
=> feat: Add document loaders module

Cargo.toml, src/vectorstore/mod.rs, src/vectorstore/surrealdb/builder.rs, src/vectorstore/surrealdb/mod.rs, src/vectorstore/surrealdb/surrealdb.rs
Surrealdb is written in rust and can be used as a in memory db, embedded into the binary similar to sqlite with rocksdb/surrealkv or distributed with foundation db or tikv. This should open up langchain-rust for interesting scenarios.
Example usage:
```toml
langchain-rust = { version = "2.3.0", features = ["surrealdb"] }
tokio = { version = "1.36.0", features = ["full"] }
surrealdb = { version = "1.2.2", features = [ "kv-mem", "kv-rocksdb", "kv-tikv" ] } # choose the backend that you wish.
```
Start surrealdb in the cli. Ignore this if using memory or rocksdb directly in rust code.
```
surreal start --allow-all --strict --bind=127.0.0.1:8000 --username=root --password=root file://./embeddings.db
```
<details>
<summary> rust code</summary>
```rust
use std::collections::HashMap;
use …
```
=> add support for surrealdb as vector store

examples/streaming_from_chain.rs, src/chain/chain_trait.rs, src/chain/llm_chain.rs, src/language_models/llm.rs, src/llm/openai/mod.rs
This commit introduces a streaming functionality in the language chain. A new 'stream' function is added to the Chain trait that is expected to be implemented by all chains. A corresponding 'stream' implementation is provided in the LLMChain struct as well. The LLM trait has also been updated to include a 'stream' function. The 'stream' function is also implemented in the OpenAI struct, where the chat API is leveraged to create a stream of response generation.
In addition, a new example of usage of the streaming API has been included under the examples directory.
=> feat: Add streaming functionality to the language chain

.github/workflows/ci.yml
At some point we probably want to group the tests that requires LLM and that doesn't require so we can run the non LLM ones in the CI. For now build it but don't run any tests.
=> build tests but don't run

src/chain/llm_chain.rs
I found an issue with the memrory manage in llm_chain to prevent errors I delete the memory from llm_chain
the error was it was only looking for an "input" if it was no input it will fail
also it was adding only the input to the memory, istead of the complete prompt
if someone want to use memory shoud use the conversational chain which was build to use memory.
evaluete if in the future we can suport memory in the llm_chian, maybe is better to leave the memory mangement to then chain using the llm_chain.
=> fix(llm_chain): fix memory

.github/workflows/ci.yml, src/agent/chat/chat_agent.rs, src/chain/conversational/mod.rs, src/chain/question_answering.rs, src/chain/sequential/chain.rs, src/vectorstore/surrealdb/builder.rs
This enabled running tests in CI. For those that require OpenAI or network requests it is suggested to add `#[ignore]` attribute. This will avoid running this tests when using `cargo test`. If you want to run all tests use `cargo test && cargo test -- --ignored`.
Probably worth investing in Mock Open AI at some point so we can potentially run all tests.
=> run tests in ci but ignore openai tests

examples/streaming_from_chain.rs
Update the `streaming_from_chain` to correctly stream the response in console.
=> improve streaming_from_chain example to correctly stream the response

src/chain/llm_chain.rs, src/language_models/llm.rs, src/llm/openai/mod.rs
changing with_option of llm trait to add_options for redability
=> refactor(llm): changing with_option of llm trait to add_options

src/document_loaders/csv_loader/csv_loader.rs, src/document_loaders/document_loader.rs, src/document_loaders/pdf_loader/lo_loader.rs, src/document_loaders/text_loader/text_loader.rs, src/text_splitter/markdown_splitter.rs, src/text_splitter/text_splitter.rs, src/text_splitter/token_splitter.rs
This change introduces asynchronous function calls in the csv_loader, text_loader, pdf_loader and other document loaders. Also the TextSplitter trait plus its implementations are now async. This modification will make the tasks of document loading and text splitting run concurrently, potentially improving the performance of the entire document processing pipeline.
=> feat: make document loaders and text splitters run asynchronously

Cargo.toml, README.md, examples/vector_store_postgres.rs, examples/vector_store_sqlite.rs, src/vectorstore/mod.rs, src/vectorstore/sqlite_vss/builder.rs, src/vectorstore/sqlite_vss/mod.rs, src/vectorstore/sqlite_vss/sqlite_vss.rs
This should be compatible with langchain python except for the trigger name. I think it is a bug there but not an expert in sqlite. refer to https://github.com/langchain-ai/langchain/blob/b617085af0d14468d5418176d4235229c2c12ffa/libs/community/langchain_community/vectorstores/sqlitevss.py#L26
you do need to manually install sqlite-vss libraries from https://github.com/asg017/sqlite-vss. Easiest way is to download the dynamic libraries and set it in the same path as the binary. your OS might block the libraries since it is download from the internet. I have filed an issue on sqlx site, so we can statically link the extension in the future when it is supported. https://github.com/launchbadge/sqlx/issues/3147
=> Add support for sqlite_vss as vector store

Cargo.toml, examples/fastembed.rs, src/embedding/error.rs, src/embedding/fastembed/fastembed.rs, src/embedding/fastembed/mod.rs, src/embedding/mod.rs
This commit includes changes made to add support for FastEmbed text embedding. We've added a new dependency 'fastembed' in our Cargo.toml. New error message has been added in 'error.rs' to handle any FastEmbed related errors. Created a new struct 'FastEmbed' under 'fastembed.rs' that utilizes the FastEmbed library for text embedding. Also, added FastEmbed related modules and updated embedding/mod.rs accordingly. Tests for FastEmbed have been included as well.
=> feat: add FastEmbed text embedding support

Cargo.toml, README.md, examples/git_commits.rs, src/document_loaders/error.rs, src/document_loaders/git_commit_loader/git_commit_loader.rs, src/document_loaders/git_commit_loader/mod.rs, src/document_loaders/mod.rs
Test is commented and ignored for now.
Currently all the commits are loaded in memory as gix library when walking iterator is not thread safe.
In the future we can add commit date/time, files that were modified including diff.
=> Add support for git commit loader

src/chain/conversational/builder.rs, src/chain/error.rs, src/chain/llm_chain.rs, src/chain/sql_datbase/builder.rs, src/language_models/llm.rs, src/lib.rs, src/llm/openai/mod.rs, src/output_parsers/error.rs, src/output_parsers/markdown_parser.rs, src/output_parsers/mod.rs, src/output_parsers/output_parser.rs, src/output_parsers/simple_parser.rs, src/prompt/chat.rs, src/prompt/mod.rs
Made changes in the source code to add output parser in the conversational chain builder. Updated methods in chain builder, SQL database chain builder, and LLM chain builder to include output parser. Added error handling for output parser error in llm and chain module. Added new module output_parsers with simple and markdown parsers. Added tests for markdown parser. Updated prompt chat module to change the conversion from structs to traits using Into to From for better rust convention.
#110
=> feat: added output parser in the chain builder

Cargo.toml
Recently versions of FastEmbed have added some [new quantized models](https://github.com/Anush008/fastembed-rs/blob/ddb09017ef7c8abc6ea09b45c422d01aa502c02a/src/models.rs#L4-L45).
Pinning the version to `"3"` allows users to have access to any newer models that could be added in `v3`.
Breaking changes will always have a major version bump.
=> chore(deps): Pinned FastEmbed version to "3"

examples/sql_chain.rs
Fixes a typo in a comment in the `sql_chain` example.
=> chore: fix typo "slq_chain" -> "sql_chain"

src/llm/claude/client.rs
The default ENV var for Claude's API key was spelled wrong. This PR fixes it.
=> Fix spelling.

Cargo.toml, examples/git_commits.rs, src/document_loaders/git_commit_loader/git_commit_loader.rs
=> use channels for git commit loader to stream per commit instead of loading all commits in memory

src/llm/openai/mod.rs
Add the new OpenAI model. I verified that it builds and the AI model string is correct and calls go to the new model. 
Looks like the CI build error is unrelated and is impacting #152 as well.
=> Add new GPT4o model.

.gitignore, Cargo.toml, README.md, examples/embedding_ollama.rs, examples/llm_ollama.rs, src/embedding/error.rs, src/embedding/mod.rs, src/embedding/ollama/ollama_embedder.rs, src/language_models/error.rs, src/llm/claude/client.rs, src/llm/mod.rs, src/llm/ollama/client.rs, src/llm/ollama/mod.rs, src/llm/ollama/openai.rs
This PR integrates [Ollama-rs](https://github.com/pepperoni21/ollama-rs) and feature-gates it with the `ollama` feature.
- Re-Implements `OllamaEmbedder` using the new client, the `embedding_ollama.rs` example is working.
- Implements the `language_models::llm::LLM` trait for `Ollama`, the `llm_ollama.rs` example is working.
- Also allows OpenAI compatible Ollama usage by implementing `async_openai::config::Config` for `OllamaConfig`, this part is not feature-gated as it does not require Ollama-rs package.
- Closes #148 : Initially we had talked about adding an option to auto-pull a model if it does not exist and such, but with Ollama-rs integrated, we can simply leave that to the user. The pull code is a simple one-liner using the Ollama-rs client, and our tools request the client be …
=> Ollama-rs integration

src/chain/conversational/mod.rs
This pull request fixes a typo in the `ConversationalChain` struct where the method name `pompt_builder` was misspelled. The correct method name is `prompt_builder`.
=> Fix typo in ConversationalChain prompt_builder method name

README.md, examples/open_ai_tools_agent.rs, src/tools/duckduckgo/duckduckgo_search.rs, src/tools/duckduckgo/mod.rs, src/tools/mod.rs
This introduces duck duck go search tool. Here is the langchain python equivalent. https://github.com/langchain-ai/langchain/blob/0214246dc69dd2d4e11fd567308f666c220cfb0d/libs/community/langchain_community/tools/ddg_search/tool.py#L43
I'm only porting DuckDuckGoSearchResults and not DuckDuckGoSearchRun. The main difference between them seems to be one returning JSON while other is returning string. 
My tests with llama3 and mistral both seems to be able to extract information from JSON and return the correct response. Phi3 wasn't good at figuring it out. In the future we can easily add DuckDuckGoSearchRun if needed.
=> add DuckDuckGoSearchResults Tool

src/llm/ollama/client.rs
Issue: The modules in the ollama_rs library are inaccessible. As a result, creating for example generation options to pass to the `.with_options` method of the Ollama client is not possible.
This pull request resolves the visibility issue with the ollama_rs crate, making it accessible for use.
=> fix: make ollama_rs crate visible

Cargo.toml
The `Ollama` client itself at `0.2.0` is not compatible with `0.1.9`, therefore it becomes a problem when one wants to use Ollama-rs on its own and together with LangChain.
=> chore: bump ollama `0.1.9` to `0.2.0`

Cargo.toml, src/vectorstore/qdrant/qdrant.rs
This PR does two things.
First of all it bumps the Qdrant client dependency to the latest available; 1.9.
It also preemptively changes the way we convert payloads to prevent a compilation error once Qdrant client 1.10 is released.
=> Bump Qdrant dependency to 1.9, preemptively fix 1.10 compiler error

src/llm/ollama/client.rs, src/schemas/messages.rs
When I wanted to call the LLaVA model, I found that I could not pass the images to ollama, so I added the images field to the Message struct and implemented the mapping to ollama ChatMessage.
=> Support adding images to Message and mapping to ollama ChatMessage images.

Cargo.toml, examples/vector_store_qdrant.rs, src/vectorstore/qdrant/builder.rs, src/vectorstore/qdrant/qdrant.rs
With [Qdrant 1.10](https://github.com/qdrant/qdrant/releases/tag/v1.10.0) we released a new API client for Rust. The client is easier to work with, and more importantly, a lot more robust to prevent breakage with future updates.
This PR bumps the Qdrant client to use the new API client.
Note that this still supports older Qdrant versions before 1.10.
Continuation after: <https://github.com/Abraxas-365/langchain-rust/pull/175>
=> Bump Qdrant dependency to 1.10 with new API client

src/llm/claude/client.rs, src/llm/claude/models.rs, src/schemas/messages.rs
Fixes claude system message error when using it an LLM Agent.
`'messages: Unexpected role "system". The Messages API accepts a top-level 'system' parameter, not "system" as an input message role.'`
How to reproduce error: replace OpenAI with Claude as the LLM in this example:
https://github.com/Abraxas-365/langchain-rust/blob/main/examples/open_ai_tools_agent.rs
=> fix: claude system message error

Cargo.toml, src/document_loaders/error.rs, src/document_loaders/mod.rs, src/document_loaders/pdf_loader/mod.rs
Make lopdf optional feature. I wasn't able to make this work with some of the pdfs I have. 
I will send another PR to have another PDF text extractors.
https://crates.io/crates/pdf-extract Seems to work but looking at issues has few panics.
Probably need to use something like https://crates.io/crates/pdfium-render.
=> make lopdf optional

src/language_models/options.rs, src/llm/openai/mod.rs, src/schemas/tools_openai_like.rs
We have to change to tool_choice, because the functions are inserted as tools.
I also added the named options to force the LLM to use a tool.
=> tool_choice instead of function_call

src/llm/openai/mod.rs
Set the default model to gpt4o mini  as it is cheaper, more capable, multimodal, and just as fast. See [Model Overview](https://platform.openai.com/docs/models/gpt-3-5-turbo)
=> set default model to gtp4omini

Cargo.toml, README.md, src/document_loaders/error.rs, src/document_loaders/mod.rs, src/document_loaders/pdf_loader/mod.rs, src/document_loaders/pdf_loader/pdf_extract_loader.rs
Adding a new pdf-extract loader as using lopdf directly it couldn't load some files.
Had to bump the version of lopdf down as pdf-extract uses a lower version. Ideally if pdf-extract exposed lopdf::Document then we didn't have to decrease the version - https://github.com/jrmuizel/pdf-extract/pull/44
To extract by pages need https://github.com/jrmuizel/pdf-extract/pull/93.
=> add pdf-extract loader

.gitignore, src/document_loaders/dir_loader.rs, src/document_loaders/source_code_loader/source_code_loader.rs
Context:
Relates to https://github.com/Abraxas-365/langchain-rust/issues/203
=> Changed Exclude String filters in favour of Callback Functions.

src/schemas/agent.rs
Noticed this when trying to debug the library.
=> add #[derive(Debug)] for AgentEvent

src/vectorstore/pgvector/pgvector.rs
The current query is not sorted by score from highest to lowest, resulting in a query for the first N entries that may not pick up data with a high score.
=> Fixed an error in sorting vector data queries by score.

examples/llm_ollama.rs, src/llm/ollama/client.rs, src/llm/ollama/openai.rs
Default to llama3.2 for ollama since it is very fast and supports tooling including those running in just CPU. In my test 1b seems to fails at following instructions on JSON so sticking with 3b.
=> default to llama 3.2 for ollama

Cargo.toml, README.md, examples/git_commits.rs, examples/vector_store_sqlite_vec.rs, examples/vector_store_sqlite_vss.rs, src/vectorstore/mod.rs, src/vectorstore/sqlite_vec/builder.rs, src/vectorstore/sqlite_vec/mod.rs, src/vectorstore/sqlite_vec/sqlite_vec.rs
support sqlite-vec, I basically referenced the code of sqlite-vss, except for using the format supported by sqlite-vec for table creation,  i'm not sure it absolutely right, but i have run in my own project.
=> [BREAKING CHANGE] feat: support sqlite-vec (#216)

Cargo.toml, README.md, src/document_loaders/html_loader/html_loader.rs, src/document_loaders/html_to_markdown_loader/html_to_markdown_loader.rs, src/document_loaders/html_to_markdown_loader/mod.rs, src/document_loaders/mod.rs
This uses [htmd](https://crates.io/crates/htmd) which is a port of JS library [turndown.js](https://github.com/mixmark-io/turndown) that converts html to markdown. While we have an existing HTMLoader that converts HTML to Plain Text, having markdown can help with better markdown chunking based on headings. LLMs these days are also better at understanding markdown which may yield better result than using plain text.
Since this introduces a new crate I have put it under a feature flag to avoid unnecessary compilation.
=> add HtmlToMarkdownLoader

src/vectorstore/pgvector/pgvector.rs
This change seems to fix the issue #268 , but I want to note that it's likely a symptom, not a core issue. The current design forces the user to have a "strongly"-typed metadata implementation instead of relying on rust datatypes with macro-base Serialize/Deserialize implementations. As a thought, it may be better to update the VectorStore trait with the associated type for Metadata.
=> Fix redundant double-quoting in pgvector filters #268

Cargo.toml, src/document_loaders/source_code_loader/language_parsers.rs
- Support for Scala, Java, Kotlin, and CSharp
- Use cpp parser to parse .h file: C++ header can end with .h; While C parser may not work with C++ header, cpp parser will work with C files just fine.
=> More popular programming languages to source loader

src/vectorstore/opensearch/opensearch.rs, src/vectorstore/options.rs, src/vectorstore/pgvector/builder.rs, src/vectorstore/pgvector/pgvector.rs, src/vectorstore/qdrant/qdrant.rs, src/vectorstore/sqlite_vec/sqlite_vec.rs, src/vectorstore/sqlite_vss/sqlite_vss.rs, src/vectorstore/surrealdb/surrealdb.rs, src/vectorstore/vectorstore.rs
I was using the library to implement a RAG-application with a `pgvector` vector store. Current implementation was lacking in filtering facility for `pgvector`, and only allows for equality comparisons chained with `AND` in sql. Filtering is abstracted over a serializable JSON AST (`serde_json::Value`), which may be appropriate for some of the vector store implementations in the library, but not for all. I reasoned that adding an associated type to the trait would be the most logical way to approach it since it allows us to implement custom filtering for some of the stores (as I do with `pgvector` in this PR) but keep the old behavior for others. 
I also added an implementation of `pgvector` filter that fits my needs, and allows for further extendability. Please see the following links to …
=> Add flexibility to Store trait + better pgvector filtering

src/agent/executor.rs
The HashMap created by `AgentExecutor::get_name_to_tools()` uses `tool.name().trim().replace(" ", "_")` for keys
https://github.com/Abraxas-365/langchain-rust/blob/60c71258d8a40c278f2867f6b4d3871265f6e638/src/agent/executor.rs#L59-L66
But just `tool.name()` is used here, which means any tools that have spaces in their names will not be found.
https://github.com/Abraxas-365/langchain-rust/blob/60c71258d8a40c278f2867f6b4d3871265f6e638/src/agent/executor.rs#L99-L104
This pull request simply adds `.trim().replace(" ", "_")` for the `.get()` call
Accidentally deleted #292, same pull request
=> fix: inconsistent tool name handling in agent executor
