- Cargo.toml
- README.md
- src/tools/sql/mod.rs
- src/vectorstore/mod.rs
I'm ok to make this default if needed. This could save time on compilation if not using Postgres.
> make postgres optional

- src/embedding/openai/openai_embedder.rs
Add support for custom base_url and model for OpenAI embedding. This change allows users to specify their own base URL and model when using the OpenAiEmbedder struct. This will make it easy to get started with self-hosted RAGs.
Closes #21
> feat(openai): Add support for custom base_url and model

- src/embedding/openai/openai_embedder.rs
- Refactored error handling in OpenAiEmbedder.rs to include logging and proper error message retrieval from response body.
> chore: update error handling in OpenAiEmbedder.rs

- src/llm/openai/mod.rs
> fix: replace use of deprecated struct async_openai #33

- Cargo.toml
- src/document_loaders/csv_loader/csv_loader.rs
- src/document_loaders/csv_loader/mod.rs
- src/document_loaders/mod.rs
- src/document_loaders/test_data/test.csv
- src/schemas/document.rs
- Added csv dependency version 1.3.0 to Cargo.toml
- Created CsvLoader struct in csv_loader.rs with methods for loading documents from CSV
- Added mod.rs file for csv_loader module
- Updated mod.rs in document_loaders directory to include csv_loader module
- Updated Document struct in document.rs to accept generic page_content parameter
> feat: Add CSV loader

- Cargo.toml
- examples/agent.rs
- examples/wolfram_tool.rs
- src/tools/mod.rs
- src/tools/wolfram/mod.rs
- src/tools/wolfram/wolfram.rs
Adds a tool to call the wolfram API, more specifically the full results endpoint. Tool returns JSON string with answer pods and sub-pods plain text (See more at [Wolfram Documentation](https://products.wolframalpha.com/api/documentation)).
> Wolfram Tool implementation

- renovate.json
> update renovatebot schedule for once a week and wait for 3 days stablity

- Cargo.toml
- src/document_loaders/error.rs
- src/document_loaders/html_loader/html_loader.rs
- src/document_loaders/html_loader/mod.rs
- src/document_loaders/mod.rs
- src/document_loaders/test_data/example.html
Use [readability](https://crates.io/crates/readability) to extract text from html.
> Add HtmlLoader

- src/llm/claude/client.rs
- Added the Clone trait to the Claude struct in client.rs file. No context provided.
> chore: Add Clone trait to Claude struct in client.rs

- examples/conversational_retriever_chain_with_vector_store.rs
- examples/conversational_retriever_simple_chain.rs
- src/chain/conversational_retrieval_qa/builder.rs
- src/chain/conversational_retrieval_qa/conversational_retrieval_qa.rs
- src/chain/conversational_retrieval_qa/mod.rs
- src/chain/conversational_retrival_qa/mod.rs
- src/chain/error.rs
- src/chain/mod.rs
- src/chain/question_answering.rs
- src/schemas/mod.rs
- src/schemas/retrievers.rs
Hi,
Firstly, thank you for making this project.  I have been wanting a Rust "port" of LangChain and I just never had the time or wherewithal to do it myself.
Second, I apologize in advance for any sense of hubris this PR might convey.  I was working with some of the examples and I noticed some spelling changes that were tripping me up.    This PR attempts to clean up the spelling changes that I saw.
I don't know if they set intentionally so please free to close this PR without prejudice if it doesn't suit.
> Fix some typos in package and struct names

- .gitignore
- Cargo.toml
- README.md
- src/document_loaders/dir_loader.rs
- src/document_loaders/mod.rs
- src/document_loaders/source_code_loader/language_parsers.rs
- src/document_loaders/source_code_loader/mod.rs
- src/document_loaders/source_code_loader/source_code_loader.rs
- src/document_loaders/test_data/example.rs
Add source code loader like https://python.langchain.com/docs/integrations/document_loaders/source_code/
> feat: add source code loader

- Cargo.toml
- src/document_loaders/source_code_loader/language_parsers.rs
language parser support more languages
> feat: language parser support more languages

- examples/conversational_chain.rs
just fixing https://github.com/Abraxas-365/langchain-rust/issues/143
> spelling error fix

- Cargo.toml
- src/document_loaders/source_code_loader/language_parsers.rs
- src/document_loaders/source_code_loader/source_code_loader.rs
> add support for typescript in source code loader via tree-sitter

- examples/wolfram_tool.rs
- src/agent/chat/builder.rs
- src/agent/chat/chat_agent.rs
- src/agent/executor.rs
- src/agent/open_ai_tools/agent.rs
- src/agent/open_ai_tools/builder.rs
- src/chain/chain_trait.rs
- src/chain/conversational/mod.rs
- src/chain/conversational_retrieval_qa/conversational_retrieval_qa.rs
- src/chain/llm_chain.rs
- src/chain/sequential/chain.rs
- src/chain/sql_datbase/builder.rs
- src/document_loaders/dir_loader.rs
- src/document_loaders/pandoc_loader/pandoc_loader.rs
- src/language_models/mod.rs
- src/llm/claude/client.rs
- src/llm/ollama/openai.rs
- src/memory/dummy_memory.rs
- src/prompt/chat.rs
- src/schemas/memory.rs
- src/schemas/messages.rs
- src/semantic_router/index/memory_index.rs
- src/semantic_router/route_layer/route_layer.rs
- src/tools/command_executor/command_executor.rs
- src/tools/scraper/scraper.rs
- src/tools/sql/sql.rs
- src/tools/text2speech/openai/client.rs
- src/tools/wolfram/wolfram.rs
Some from clippy, some flagged by my editor and some found looking at the code.
This includes a backward-breaking change (DummyMemory was misspelt).
I'm not sure how you want to handle this.
> Fix some warnings and style

- src/chain/options.rs
- src/language_models/options.rs
- src/llm/claude/models.rs
Based on changelog of from https://github.com/Abraxas-365/langchain-rust/pull/172
> Change max_tokens from u16 to u32 for larger context window in recent models

- Cargo.toml
- README.md
- examples/embedding_mistralai.rs
- src/embedding/error.rs
- src/embedding/mistralai/mistralai_embedder.rs
- src/embedding/mistralai/mod.rs
- src/embedding/mod.rs
Adds MistralAI embedder (llm to follow)
> Add optional MistralAI embedder

- src/chain/conversational_retrieval_qa/builder.rs
- src/chain/conversational_retrieval_qa/conversational_retrieval_qa.rs
fixed typo named chian and changed it to chain
> fix: chain typo - changed from chian to chain

- src/agent/open_ai_tools/agent.rs
> fix(openai): messages with role 'tool' must be a response to a preceding message with 'tool_calls' error

- src/agent/executor.rs
This also better handles adding the original user input message into the agent memory.  It avoids having the input string getting wrapped in additional quotes (due to json serialization).
> feat(agent): Add agent tools call messages in the agent memory.  Fixes #245

- README.md
Commit 7dc81a60dd5435815cd66c5c818b2a497b0fbdcb renamed the sqlite example. This PR adjusts sources to changes.
> fix: update sqlite example

- src/document_loaders/error.rs
- src/language_models/options.rs
- src/llm/openai/mod.rs
- src/schemas/convert.rs
- src/schemas/mod.rs
- src/schemas/response_format_openai_like.rs
- src/schemas/tools_openai_like.rs
- add response_format argument as an alternative to function calls
- add convert functions for OpenAI like schemas
> OpenAI like 'response_format'

- src/vectorstore/qdrant/qdrant.rs
Because I need to filter entries by some payload field to recreate one specific "document" chunks stored in the qdrant vector DB (and obviously you cannot filter by metadata json object structure) i need to extend payload so I'm using filter when calling "add_document" because I would use same filter.
We could extend vectore store struct of vectoreStoreOptions adding `.with_payload` that would do the same thing.
> fix(qdrant): Extend qdrant document payload 
